# Generated by Django 4.2.13 on 2024-06-25 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_phone'),
        ('book', '0003_book_is_available_booktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.user'),
        ),
    ]
