# Generated by Django 4.2.13 on 2024-06-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return'), ('Request', 'Request')], max_length=10),
        ),
    ]
