# Generated by Django 4.2.13 on 2024-06-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_alter_booktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
