# Generated by Django 4.2.13 on 2024-07-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0012_alter_booktransaction_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('Borrow', 'Borrow'), ('Return', 'Return'), ('Request', 'Request')], default='Borrow', max_length=10),
        ),
    ]
