# Generated by Django 4.2.13 on 2024-07-02 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_customuser_phone'),
        ('book', '0013_alter_booktransaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktransaction',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book.book'),
        ),
        migrations.AlterField(
            model_name='booktransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='account.user'),
        ),
    ]
